- name: Deploy dockerized app
  hosts: app_servers
  become: true

  vars:
    image: ""
    app_name: myapp
    container_port: 8080
    host_port: 8080

  tasks:
    - name: Pull image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Stop & remove existing container
      community.docker.docker_container:
        name: "{{ app_name }}"
        state: absent
        force_kill: yes
      ignore_errors: yes

    - name: Run container
      community.docker.docker_container:
        name: "{{ app_name }}"
        image: "{{ image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port }}:{{ container_port }}"
